// Who We Help. Entries with `page` get a dedicated landing page at /<page>/.
// `role` must match an option in the enquiry form's "I am a" list.

export const audiences = [
  {
    name: 'MBBS Students',
    role: 'MBBS Student',
    icon: 'student',
    short: 'Research projects, methodology guidance, literature reviews, statistics and academic presentation support.',
    page: 'for-mbbs-students',
    headline: 'Research support for MBBS students',
    intro: 'Your first research project — ICMR-STS, a college project, or a paper you want to publish — is a chance to learn research properly. We help you understand each step instead of guessing.',
    challenges: [
      'Choosing a feasible topic with limited time and resources',
      'No formal training yet in study design or statistics',
      'Understanding ethics approval and consent requirements',
      'Writing a clear proposal or report for the first time',
      'Balancing research with a demanding academic schedule',
    ],
    services: ['research-methodology', 'literature-search', 'biostatistics', 'viva-presentation', 'academic-editing'],
    workflow: ['Share your idea or topic', 'Methodology and feasibility review', 'Proposal and data collection plan', 'Analysis and interpretation support', 'Report or presentation review'],
    deliverables: ['Refined research question and objectives', 'Proposal review with feedback', 'Analysis output with explanation', 'Presentation or poster review'],
    faqs: [
      { q: 'Can you help with a short-term studentship proposal?', a: 'Yes. We can help you structure the proposal, refine objectives and plan a realistic sample size and timeline within the scheme’s requirements.' },
      { q: 'I have never done statistics. Is that a problem?', a: 'Not at all. We explain the analysis in plain language so you understand what was done and why.' },
    ],
  },
  {
    name: 'MD / MS Students',
    role: 'MD/MS Student',
    icon: 'stethoscope',
    short: 'Thesis planning, protocol development, statistics, manuscript preparation and publication support.',
    page: 'for-md-ms-students',
    headline: 'Thesis and research support for MD / MS residents',
    intro: 'From synopsis to viva, we support you through each stage of your postgraduate thesis with structured guidance, professional statistics and careful review — while you remain the author.',
    challenges: [
      'Finalising a synopsis quickly after joining residency',
      'Sample size justification for the IEC',
      'Data collection alongside heavy clinical duties',
      'Choosing and interpreting the right statistical tests',
      'Meeting university formatting rules and deadlines',
      'Converting the thesis into a publishable paper',
    ],
    services: ['research-protocol', 'thesis-guidance', 'biostatistics', 'academic-editing', 'viva-presentation', 'manuscript-support'],
    workflow: ['Synopsis and sample size', 'Data collection plan and proforma', 'Statistical analysis', 'Draft review and formatting', 'Viva preparation', 'Manuscript from thesis'],
    deliverables: ['Protocol review and sample size calculation', 'Statistical analysis plan and output', 'Chapter-wise draft feedback', 'Formatting check', 'Mock viva'],
    faqs: [
      { q: 'At what stage should I contact you?', a: 'Any stage — but the earlier the better. Getting the design and sample size right at the synopsis stage avoids problems later.' },
      { q: 'Do you follow my university’s guidelines?', a: 'Yes. Share your university’s thesis guidelines and we follow them for structure and formatting.' },
    ],
  },
  {
    name: 'DNB Residents',
    role: 'DNB Resident',
    icon: 'hospital',
    short: 'Hospital-based research, data analysis, manuscript preparation and research guidance.',
    page: 'for-dnb-residents',
    headline: 'Research support for DNB residents',
    intro: 'Hospital-based research has its own practical realities — registries, record-based data and busy clinical services. We help you design around them and meet your thesis and publication requirements.',
    challenges: [
      'Working with retrospective or record-based hospital data',
      'Protocol and thesis submission timelines',
      'Limited in-house biostatistics support',
      'Thesis-to-publication requirements',
    ],
    services: ['research-protocol', 'biostatistics', 'thesis-guidance', 'manuscript-support', 'publication-support'],
    workflow: ['Protocol review', 'Data structure and cleaning plan', 'Analysis and interpretation', 'Thesis review and formatting', 'Manuscript and journal selection'],
    deliverables: ['Protocol feedback', 'Clean analysis dataset structure', 'Results tables and figures', 'Manuscript review'],
    faqs: [
      { q: 'Can you work with Excel data from hospital records?', a: 'Yes. We help you structure, code and clean the data before analysis. Please remove patient identifiers before sharing.' },
    ],
  },
  { name: 'DM / MCh Students', role: 'DM/MCh Student', icon: 'heart', short: 'Advanced study design, complex statistics, systematic reviews and high-quality publication preparation.' },
  { name: 'PhD Scholars', role: 'PhD Scholar', icon: 'microscope', short: 'Proposal development, methodology, advanced analysis, systematic reviews and thesis editing.' },
  {
    name: 'MSc Nursing Students',
    role: 'Other',
    icon: 'nurse',
    short: 'Research proposals, questionnaire design, data analysis and dissertation guidance.',
    page: 'for-nursing-students',
    headline: 'Research support for nursing students',
    intro: 'MSc Nursing and BSc Nursing research often involves questionnaires, educational interventions and descriptive or quasi-experimental designs. We help you plan, analyse and present your study properly.',
    challenges: [
      'Designing and validating a questionnaire or checklist',
      'Planning pre-test / post-test and quasi-experimental designs',
      'Choosing appropriate statistics for Likert-scale data',
      'Writing the review of literature and methodology chapters',
    ],
    services: ['research-methodology', 'research-protocol', 'biostatistics', 'thesis-guidance', 'academic-editing'],
    workflow: ['Problem statement and objectives', 'Tool development and content validity', 'Pilot study planning', 'Analysis and interpretation', 'Dissertation review'],
    deliverables: ['Objectives and hypotheses review', 'Tool structure feedback', 'Statistical output with interpretation', 'Dissertation formatting check'],
    faqs: [
      { q: 'Can you help with content validity of my tool?', a: 'We can explain the process, help you prepare the validation format for experts, and analyse the responses (e.g. CVI).' },
    ],
  },
  { name: 'Allied Health Students', role: 'Other', icon: 'users', short: 'Physiotherapy, pharmacy, public health and allied health research methodology and statistics support.' },
  {
    name: 'Medical Faculty',
    role: 'Faculty',
    icon: 'award',
    short: 'Research methodology, manuscript editing, systematic reviews, statistical consulting and publication support.',
    page: 'for-medical-faculty',
    headline: 'Research consulting for medical faculty',
    intro: 'Faculty juggle teaching, clinical work, administration and research expectations. We act as an extension of your research team — methodology, statistics, systematic reviews and manuscript support on your schedule.',
    challenges: [
      'Limited protected time for research',
      'Supervising many postgraduate theses at once',
      'Need for reliable statistical consulting',
      'Publication expectations for promotion and grants',
    ],
    services: ['biostatistics', 'systematic-review', 'manuscript-support', 'publication-support', 'research-methodology', 'academic-editing'],
    workflow: ['Scoping call', 'Written scope and timeline', 'Analysis or review work', 'Manuscript support', 'Submission and revision support'],
    deliverables: ['Statistical consulting reports', 'Meta-analysis outputs', 'Edited manuscripts', 'Journal shortlists'],
    faqs: [
      { q: 'Can you support departmental or multi-centre studies?', a: 'Yes. We can support study design, data management planning and analysis for departmental and collaborative studies.' },
    ],
  },
  {
    name: 'Researchers',
    role: 'Researcher',
    icon: 'flask',
    short: 'Study design, biostatistics, literature synthesis and publication preparation.',
    page: 'for-researchers',
    headline: 'Support for hospital and independent researchers',
    intro: 'Whether you are a clinician-researcher, part of a hospital research unit, or working independently, we provide flexible methodology, biostatistics and publication support.',
    challenges: [
      'Access to specialist biostatistics',
      'Keeping methods transparent and reproducible',
      'Literature synthesis for new projects',
      'Publishing in suitable, credible journals',
    ],
    services: ['research-methodology', 'biostatistics', 'systematic-review', 'literature-search', 'manuscript-support', 'publication-support'],
    workflow: ['Requirement review', 'Scope and plan', 'Milestone-based work', 'Review and explanation', 'Publication preparation'],
    deliverables: ['Statistical analysis plans and outputs', 'Search strategies', 'Manuscript feedback', 'Journal shortlists'],
    faqs: [
      { q: 'Do you sign confidentiality agreements?', a: 'Yes. We treat all research material as confidential and can sign a non-disclosure agreement on request.' },
    ],
  },
  { name: 'Hospital Researchers', role: 'Researcher', icon: 'hospital', short: 'Registry and record-based studies, audits, quality-improvement projects and analysis support.' },
  { name: 'Clinical Research Teams', role: 'Researcher', icon: 'team', short: 'Statistical analysis plans, sample size, data analysis and reporting support for study teams.' },
];
