// Reusable FAQ database. `tags` decide where an FAQ also appears
// (home, pricing, specific service slugs). Answers avoid guaranteed outcomes.

export const faqs = [
  { cat: 'Services', q: 'Do you provide statistical analysis?', a: 'Yes. We provide sample size calculation, descriptive and inferential statistics, regression, survival and diagnostic test analysis in SPSS, R, STATA or Python, along with plain-language interpretation of every result.', tags: ['home', 'biostatistics'] },
  { cat: 'Services', q: 'Can you help me choose a research topic?', a: 'Yes. We help you evaluate topic ideas for relevance, feasibility, available sample and time. We do not impose a topic — the final choice is made by you and your guide.', tags: ['home', 'research-methodology'] },
  { cat: 'Services', q: 'Do you help with sample size calculation?', a: 'Yes. We calculate sample size based on your primary outcome, design and values from published literature, and document every assumption so you can justify it to your department or ethics committee.', tags: ['biostatistics', 'research-protocol'] },
  { cat: 'Services', q: 'Can you edit my manuscript?', a: 'Yes. We provide language editing, structural review, reference formatting and journal-specific formatting. All edits are tracked so you can review every change.', tags: ['manuscript-support', 'academic-editing'] },
  { cat: 'Services', q: 'Can you help with systematic reviews?', a: 'Yes — from question development and search strategy through screening, data extraction, risk-of-bias assessment, meta-analysis and PRISMA reporting.', tags: ['systematic-review'] },
  { cat: 'Services', q: 'Do you provide publication support?', a: 'Yes. We help with journal selection, formatting, cover letters and reviewer responses. We do not guarantee acceptance — publication decisions are made independently by journals.', tags: ['home', 'publication-support'] },
  { cat: 'Services', q: 'Can you help with SPSS?', a: 'Yes. We can run analyses in SPSS, share the syntax, and also teach you how to reproduce and understand the output.', tags: ['biostatistics'] },
  { cat: 'Who we work with', q: 'Do you work with MD/MS students?', a: 'Yes. MD/MS and DNB residents are among the main groups we support — from synopsis and sample size to statistics, draft review, formatting and viva preparation.', tags: ['home'] },
  { cat: 'Who we work with', q: 'Do you work with medical faculty?', a: 'Yes. We support faculty with methodology, biostatistics consulting, systematic reviews, manuscript editing and publication preparation.', tags: [] },
  { cat: 'Process', q: 'How does the consultation work?', a: 'Submit an enquiry or book a slot. A research coordinator reviews your requirement and speaks with you by phone, WhatsApp or video call. You then receive a written scope with deliverables, timeline and a quote. Work begins only after you approve it.', tags: ['home'] },
  { cat: 'Process', q: 'Can I upload my existing thesis or protocol?', a: 'Yes. You can upload PDF, DOCX, XLSX, CSV or PPTX files with your enquiry. Files are stored privately and are accessible only to authorised team members. Please remove patient identifiers from any data.', tags: ['home'] },
  { cat: 'Process', q: 'How is my data kept confidential?', a: 'Uploaded files are stored in private storage with access limited to authorised staff. We use your material only for your project and can sign a non-disclosure agreement on request. See our Data Handling Policy for details.', tags: [] },
  { cat: 'Pricing', q: 'How much does research support cost?', a: 'Pricing depends on study design, complexity, data size, number of analyses, timeline and deliverables. After a free consultation we send a written, itemised quote — there are no hidden charges.', tags: ['home', 'pricing'] },
  { cat: 'Pricing', q: 'Is the first consultation really free?', a: 'Yes. The initial consultation to understand your requirement and suggest a scope is free and carries no obligation.', tags: ['pricing'] },
  { cat: 'Pricing', q: 'Do you offer milestone-based payment?', a: 'For larger projects, payment can be linked to agreed milestones. Details are included in your written scope.', tags: ['pricing'] },
  { cat: 'Integrity', q: 'Will you write my thesis for me?', a: 'No. We provide guidance, statistical support, review and editing. You remain the author and should be able to explain every part of your work. Our Academic Integrity Policy explains what we do and do not do.', tags: ['home', 'thesis-guidance'] },
  { cat: 'Integrity', q: 'Is using research support services allowed?', a: 'Consulting a statistician, having a manuscript edited or getting methodology advice is common and accepted practice. Check your institution’s rules and acknowledge support where required — for example, statistical assistance in the acknowledgements section.', tags: [] },
];
