// Keyword landing pages. Each has unique title/intro and reuses a service's details.
export const seoPages = [
  { slug: 'medical-research-assistance', service: 'research-methodology', eyebrow: 'Medical research assistance', h1: 'Medical Research Assistance for Students, Residents and Faculty', title: 'Medical Research Assistance in India', desc: 'Structured medical research assistance — methodology, biostatistics, editing and publication preparation — for medical students, PG residents, researchers and faculty.', intro: 'End-to-end research assistance that keeps you in control of your study: from framing the question and planning the design to analysing data and preparing your manuscript.', cta: 'Tell us where you are in your research and we’ll suggest the right support.' },
  { slug: 'medical-thesis-guidance', service: 'thesis-guidance', eyebrow: 'Medical thesis guidance', h1: 'Medical Thesis Guidance for MD, MS and DNB', title: 'Medical Thesis Guidance for MD/MS & DNB', desc: 'Milestone-based medical thesis guidance: protocol, sample size, statistics, draft review, formatting and viva preparation. You remain the author.', intro: 'Structured guidance for postgraduate medical theses — planning, methodology, statistics, draft feedback, formatting and viva preparation — while you remain the author of your work.', cta: 'Share your thesis stage and deadline. We’ll propose a realistic, milestone-based plan.' },
  { slug: 'medical-research-methodology', service: 'research-methodology', eyebrow: 'Research methodology', h1: 'Medical Research Methodology Consulting', title: 'Medical Research Methodology Consulting', desc: 'Research question, study design, objectives, variables and outcomes — expert methodology consulting for medical research in India.', intro: 'Get your study design right before you start: research questions, objectives, variables, outcomes, bias and feasibility — reviewed by methodology specialists.', cta: 'Describe your study idea and we’ll review the methodology with you.' },
  { slug: 'medical-biostatistics', service: 'biostatistics', eyebrow: 'Medical biostatistics', h1: 'Medical Biostatistics Consulting', title: 'Medical Biostatistics Consulting (SPSS, R, STATA)', desc: 'Biostatistics consulting for medical research — sample size, regression, survival, diagnostic accuracy and interpretation in SPSS, R, STATA or Python.', intro: 'Professional biostatistics for clinical and medical research — from sample size calculation to regression, survival and diagnostic test analysis, with interpretation you can explain.', cta: 'Tell us about your data and objectives, and we’ll outline an analysis plan.' },
  { slug: 'medical-statistical-analysis', service: 'biostatistics', eyebrow: 'Statistical analysis', h1: 'Statistical Analysis for Medical Theses and Papers', title: 'Statistical Analysis for Medical Research', desc: 'Statistical analysis for medical theses and manuscripts: correct tests, clean tables and figures, and plain-language interpretation.', intro: 'The right statistical tests for your data, publication-quality tables and figures, and clear interpretation — for theses, dissertations and journal manuscripts.', cta: 'Share your objectives and dataset structure for a free assessment.' },
  { slug: 'medical-manuscript-editing', service: 'manuscript-support', eyebrow: 'Manuscript editing', h1: 'Medical Manuscript Editing', title: 'Medical Manuscript Editing & Formatting', desc: 'Scientific and language editing for medical manuscripts — structure, clarity, consistency, references and journal formatting.', intro: 'Careful editing for clarity, structure, consistency and journal requirements — so reviewers can focus on your science.', cta: 'Upload your manuscript for a free scope assessment.' },
  { slug: 'medical-publication-support', service: 'publication-support', eyebrow: 'Publication support', h1: 'Medical Journal Publication Support', title: 'Medical Journal Publication Support', desc: 'Journal selection, submission preparation, cover letters and reviewer responses for medical manuscripts. No guaranteed acceptance — just careful preparation.', intro: 'Choose suitable, credible journals, prepare complete submissions and respond to reviewers effectively. We never promise acceptance — we help you submit well.', cta: 'Tell us about your manuscript and target audience.' },
  { slug: 'systematic-review-support', service: 'systematic-review', eyebrow: 'Systematic review support', h1: 'Systematic Review and Meta-analysis Support', title: 'Systematic Review & Meta-analysis Support', desc: 'Support for systematic reviews and meta-analyses — search strategy, PRISMA workflow, screening, risk of bias, forest plots and manuscript preparation.', intro: 'Methodological support through each stage of a systematic review and meta-analysis, following recognised guidance such as PRISMA 2020.', cta: 'Share your review question and current stage.' },
  { slug: 'medical-research-consultant', service: 'research-methodology', eyebrow: 'Research consultant', h1: 'Talk to a Medical Research Consultant', title: 'Medical Research Consultant — Free Consultation', desc: 'Speak with a medical research consultant about your study design, statistics, thesis or publication. Free, confidential consultation.', intro: 'Speak with a medical research consultant about your study — design, statistics, thesis or publication. The first consultation is free and confidential.', cta: 'Request a free consultation and we’ll get in touch to discuss your study.' },
];
